### ISSUE TITLE
у меня не запускается скрипт challenge_0.py

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/python_challenge#1]
https://github.com/MarianMalvin/python_challenge/blob/master/challenge_0.py

**Comment by the-marian** [comment]
Как запускаете ? Пробовали запускать Пайтон интерпретатором ? Какая версия Питона ? Какую ОС используете ? Опешите инструкцию как воспроизвести ошибку ?

**Comment by iMykhailychenko** [comment]
Открываю в хроме Version 88.0.4324.150 (Official Build) (64-bit) на windows 10 pro

**Comment by the-marian** [comment]
Пробовали в других браузерах открывать ?

**Comment by iMykhailychenko** [comment]
да, в браузере на ps 4 pro тоже не работает
